[package]
name = "motd"
version = "0.1.2"
edition = "2021"

[dependencies]
base64 = "0"
colored = "2"
crossterm = "0"
gamedig = "0"
image = "0"
regex = "1"
serde = "1"
serde_json = "1"
unicode-width = "0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
